sudo: required

# Headless variable for Firefox
env:
  global:
    - MOZ_HEADLESS=1

# Use python with version 3.6
language: python

# Use Bionic Beaver 18.x
dist: bionic

# Add chrome and firefox browsers
addons:
  chrome: stable
  firefox: latest

# xvfb for virtual framebuffer --> webtestit requires graphical UI support
services:
  - xvfb

# make sure the proper python version is installed and pip updated
before_install:
  - if ! [ -f ./rxwt/webtestit ]; then
    wget --no-check-certificate  --force-directories -O rxwt/webtestit https://www.ranorex.com/wp-json/sage/v2/webtestit/app-download/?platform=linuxAppImage;
    fi
  - sudo apt-get install desktop-file-utils
  - sudo apt-get install python3-venv -y
  - sudo apt-get install python3-pip -y
  - sudo apt-get install openjdk-11-jdk -y
  - sudo apt-get install libsecret-1-0 -y
  - chmod a+x ./rxwt/webtestit

# install dependencies
# additionally we need to manually create the venv and map pip3 due to an issue with Travis
install:
  - python3 -m venv .
  - pushd bin && which pip3 | xargs ln -s && popd


# run webtestit
script: ./rxwt/webtestit run .

cache:
  directories:
    - $TRAVIS_BUILD_DIR/rxwt/ 

notifications:
  slack:
    secure: uiEUQoMcThL6EsYHYNk3JVpF10K08z++az9WXQUz+LAGY1C39BlnVoRCzxEsBcfPaDCPzosv4p4ZDnAOFGA1LUmesCd8hKXBt3NcGYEqPSNJ8IK+WrXYAaJIYOekpf7bwLlSVilJajBvrHBp+VGnnqYXgaYoqHu80Y1kPnm2Cbit+Ie4Kt2bl37S/o56bWWYxY2ZfzBBt/2ALGqm+0idSwAqjeIixBcdCwDtRO8RVXYQq3bM5jsL3bccaGJujF3YbIlPtDNNnM33lPoFpNALff7TdxvVOEWI6CbwY48P9yzCwrepKDpPNB9HshkbgCwr6I3E3CuckVWiRWo1m5zkolWgMsQNchKunZUxHsFU6x1I4QEpDup7RD6xpGJFnoc9NAyzc9jn2RBq2YDGPEkgFMj8RgxpJbCPh8P6UuHGfFCXafC03Cy1XrBa/lbp46npEoerVwtSpl//Ufmjrw2qsMaP4c3MugrWR8j1Nv/fqjn+ChlRve1RdDux4dqd8m+bW1LibfoeFPN/FFeizqWmTnrWRCemX5o13pGfx+FWbX6uUx0nFjAbDQlLWAN5iyytbRay1Cl6vxSQebNS0VfZtYinTlprtWElHeu2t/usGVK1LfZ9ZqyFidS1mmF5zqHQqCtdKbKteAVDMmFmunvxX4snlARc0FPLxuk3YFY91gY=